baseURL: http://mefju7.priv.no/blog/
languageCode: en-us
title: Snippets and tips
theme: helios
enableInlineShortcodes: true
enableEmoji: true
enableRobotsTXT: true
# sectionPagesMenu: main
markup:
  tableOfContents:
    endLevel: 5
    ordered: false
    startLevel: 1
  highlight:
    # anchorLineNos: false
    # codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineAnchors: ""
    # lineNoStart: 1
    lineNos: yes
    # lineNumbersInTable: true
    noClasses: false
    style: friendly
    tabWidth: 2
menu:
  main:
    - identifier: home
      url: /
      name: Home
      weight: -100
    - identifier: tags
      url: /tags
      name: Tags
      weight: 10001
    - identifier: categories
      url: /categories
      name: Categories
      weight: 10002
      

params:
  debug: true
  social:
    - https://github.com/matthias-p-nowak
    - https://www.linkedin.com/in/matthias-p-nowak/
  logo: img/Logo.svg
  favicon: img/Logo-svg.ico
  sass:
    - sass/blog.sass

